linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - gofmt
    - misspell
    - bodyclose
    - revive
    - gocyclo
    - whitespace
    - sqlclosecheck
    - goimports
    - unparam
    - revive
    - stylecheck
    - forbidigo
    - gci
run:
  allow-parallel-runners: true
  concurrency: 4
  tests: true

linters-settings:
  stylecheck:
    # https://staticcheck.io/docs/checks/
    checks: ["all", "-ST1000"]
  revive:
    rules:
      - name: package-comments
        disabled: true
  govet:
    disable:
      - loopclosure
  forbidigo:
    analyze-types: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/fiam/dc2)
output:
  formats:
    - format: tab
