version: "2"
run:
  concurrency: 4
  tests: true
  allow-parallel-runners: true
output:
  formats:
    tab:
      path: stdout
      colors: false
linters:
  enable:
    - bodyclose
    - forbidigo
    - gocyclo
    - misspell
    - nilnil
    - paralleltest
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    forbidigo:
      analyze-types: true
    govet:
      disable:
        - loopclosure
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - -ST1000
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/fiam/dc2)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
